---
title: "Figure 6 Replication"
author: "Cian Stryker"
date: "2/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Figure 6 time. This is harder
# tbh because they're using more
# data which I believe are coordinate
# lists. It starts with this rm(list)) 
# thing which I think just clears up R
# before you start. 

rm(list=ls())

# These are the packages they're using. I only
# know ggplot and readstat13. 

library(AER)
library(ggplot2)
library(readstata13)
library(spdep) 
library(tseries)

library(spatialreg)
```

```{r Data Loading}

# Like in Figure 5 they use the stata
# command to load in the main data. 

data <- read.dta13("./kyrgyzstan.dta")
```

```{r My Loading}

# I do this so I can actually the load the data
# so I can try and replicate as I go along. 

load("~/Replication_Project/Data/kyrgyzstan.RData")

data <- table
```

```{r Cleaning}

# Just like figure 5 they want to clean
# their data by setting them as integers and
# shifting the binary to 0 and -1.

data$affected <- as.integer(data$affected)
data$affected <- data$affected - 1
data$pd_in <- as.integer(data$pd_in)
data$pd_out <- as.integer(data$pd_out)

# This is just renaming the apc_min_distance
# variable as distance right? I'm pretty sure 
# that's what's happening. 

data$distance <- data$apc_min_distance

# This is another renaming bit of code. 

data$social_cap_retro <- data$leadership

# They prefer to subset instead of filter so
# they've done just that again. 

data_uzbek <- data[which(data$ethnicity=="Uzbek"),]

# Now they're scaling again. Note for reader or me: 
# the start of every figure and table begins much the same 
# way so my notes on things like scaling will become
# shorter as I run into the same code again and again. 

data_uzbek$pd_in_scale <- scale(data_uzbek$pd_in)
data_uzbek$dg_in_scale <- scale(data_uzbek$dg_in)
data_uzbek$pd_out_scale <- scale(data_uzbek$pd_out)
data_uzbek$dg_out_scale <- scale(data_uzbek$dg_out)
data_uzbek$cooperation_index <- rowSums(cbind(data_uzbek$pd_in_scale, 
                                              data_uzbek$dg_in_scale, 
                                              data_uzbek$pd_out_scale, 
                                              data_uzbek$dg_out_scale), na.rm=T)/4
```

```{r Stage 1}

# So to start they want to make their distance variable
# to be the negative version of apc_min_distance. Then it 
# gets a little more complicated. So essentially another 
# variable called id_psu has 196 groups. So the authors
# want to create a new data frame that is the aggregation of 
# the mean of the affected and distance variables on each 
# group of id_psu. 

data_uzbek$distance <- 1-data_uzbek$apc_min_distance
dataAgg <- aggregate(data_uzbek[,c("affected", "distance")], 
                     list(data_uzbek$id_psu),
                     mean)
```
                     
```{r Regressions}

# Now they are running regressions but on two different levels
# of analysis. One on all uzbeks and the other on just the 
# aggregated on psu level. But the key is to see how distance
# interacts with affected.  

first_stage_ind <- lm(affected ~ distance, data=data_uzbek)
first_stage_psu <- lm(affected ~ distance, data=dataAgg)
```

```{r Extraction}

# Now they are runnign the same regressions but for just distance
# on the scaled prisonner dilemma, dictator game, and overall 
# cooperation variables. 

model11 <- lm(pd_in_scale ~ distance , data=data_uzbek)
model12 <- ivreg(pd_in_scale ~ affected | apc_min_distance, data = data_uzbek)
model21 <- lm(dg_in_scale ~ distance , data=data_uzbek)
model22 <- ivreg(dg_in_scale ~ affected | apc_min_distance , data = data_uzbek)
model31 <- lm(pd_out_scale ~ distance , data=data_uzbek)
model32 <- ivreg(pd_out_scale ~ affected  | apc_min_distance , data = data_uzbek)
model41 <- lm(dg_out_scale ~ distance , data=data_uzbek)
model42 <- ivreg(dg_out_scale ~ affected  | apc_min_distance , data = data_uzbek)
model51 <- lm(cooperation_index ~ distance , data=data_uzbek)
model52 <- ivreg(cooperation_index ~ affected  | apc_min_distance , data = data_uzbek)
```

```{r More Aggregation}

# Okay so they are aggregating again like before on the psu 
# but now they are doing it for the scale variables, plus economy index,
# state index, and they social_cap_retro. Checks out. 

dataAgg <- aggregate(data_uzbek[,c("apc_min_distance", "distance", "pd_in_scale", "dg_in_scale", 
                                   "pd_out_scale", "dg_out_scale", "cooperation_index", "affected", 
                                   "economy_index", "state_index", "social_cap_retro")], 
                     list(data_uzbek$id_psu),
                     mean)

# This is just renaming the first column.

names(dataAgg)[1] <- "psu"

# Now they want to drop the NAs I think. 

dataAgg <- dataAgg[!is.na(dataAgg$social_cap_retro),] 
```

```{r Time Matrix}

# So here is the first part of the code that confuses me. 
# Also its the only part of the code I can't replicate for 
# some reason. So here is where I need Alice's help. 

# I believve they are just reading in travel times for APCs. 

ttmat <- read.matrix("Data/z.travel_time.csv", header = T, sep = ";", skip = 0)

# Then everything here is just reorganizing the data before they 
# combine it with the dataAgg from before. 

row.names(ttmat) <- ttmat[,1]
ttmat <- ttmat[,2:ncol(ttmat)]
ttmat <- ttmat[row.names(ttmat) %in% dataAgg$psu, colnames(ttmat) %in% dataAgg$psu]
ttmat_sort <- ttmat[order(as.numeric(row.names(ttmat))),]
ttmat_sort <- ttmat_sort[,order(as.numeric(colnames(ttmat_sort)))]

# Here is where I get stuck replicating. I get the error 
# "x must be a square matrix". I think they just want to use a matrix
# to simplify the data but I'm not sure. 

ttlistw <- mat2listw(ttmat_sort, row.names = NULL, style = "M")
```

```{r Formula}

# This gets harder for me now because I can't
# run and follow the code, but this seems clear 
# at least. They are creating formulars for later
# regressions. 

f1 <- pd_in_scale ~ distance 
f2 <- dg_in_scale ~ distance 
f3 <- pd_out_scale ~ distance 
f4 <- dg_out_scale ~ distance 
f5 <- cooperation_index ~ distance 
```

```{r Regressions}

# They're running more OLS regressions the same
# as before and from figure 5. 

model1 <- lm(pd_in_scale ~ distance , data=dataAgg)
model2 <- lm(dg_in_scale ~ distance , data=dataAgg)
model3 <- lm(pd_out_scale ~ distance , data=dataAgg)
model4 <- lm(dg_out_scale ~ distance , data=dataAgg)
model5 <- lm(cooperation_index ~ distance , data=dataAgg)
```

```{r Spatial Model Regressions}

# So they reorder and then procede to run a series of 
# regressions using the formulas they wrote before. Also
# I noticed that these functions are deprecated so I need
# adjust and use spatialreg package. Something else I'll 
# need Alice's help to wrap my head around. 

dataAgg <- dataAgg[order(dataAgg$psu),]
model13 <- errorsarlm(f1, data=dataAgg, ttlistw, tol.solve=1.0e-30)
model23 <- errorsarlm(f2, data=dataAgg, ttlistw, tol.solve=1.0e-30)
model33 <- errorsarlm(f3, data=dataAgg, ttlistw, tol.solve=1.0e-30)
model43 <- errorsarlm(f4, data=dataAgg, ttlistw, tol.solve=1.0e-30)
model53 <- errorsarlm(f5, data=dataAgg, ttlistw, tol.solve=1.0e-30)
```

```{r Extraction}

# Great. I understand all of this again. They are literally
# just grabbing all the info they want from thier list regression
# results. They'll move on to graphing soon. 

model11Frame <- data.frame(Variable = rownames(summary(model11)$coef),
                           Coefficient = summary(model11)$coef[, 1],
                           SE = summary(model11)$coef[, 2],
                           modelName = "PD ingroup")[2,]
model21Frame <- data.frame(Variable = rownames(summary(model21)$coef),
                           Coefficient = summary(model21)$coef[, 1],
                           SE = summary(model21)$coef[, 2],
                           modelName = "DG ingroup")[2,]
model31Frame <- data.frame(Variable = rownames(summary(model31)$coef),
                           Coefficient = summary(model31)$coef[, 1],
                           SE = summary(model31)$coef[, 2],
                           modelName = "PD outgroup")[2,]
model41Frame <- data.frame(Variable = rownames(summary(model41)$coef),
                           Coefficient = summary(model41)$coef[, 1],
                           SE = summary(model41)$coef[, 2],
                           modelName = "DG outgroup")[2,]
model51Frame <- data.frame(Variable = rownames(summary(model51)$coef),
                           Coefficient = summary(model51)$coef[, 1],
                           SE = summary(model51)$coef[, 2],
                           modelName = "Index")[2,]
model12Frame <- data.frame(Variable = rownames(summary(model12)$coef),
                           Coefficient = summary(model12)$coef[, 1],
                           SE = summary(model12)$coef[, 2],
                           modelName = "PD ingroup")[2,]
model22Frame <- data.frame(Variable = rownames(summary(model22)$coef),
                           Coefficient = summary(model22)$coef[, 1],
                           SE = summary(model22)$coef[, 2],
                           modelName = "DG ingroup")[2,]
model32Frame <- data.frame(Variable = rownames(summary(model32)$coef),
                           Coefficient = summary(model32)$coef[, 1],
                           SE = summary(model32)$coef[, 2],
                           modelName = "PD outgroup")[2,]
model42Frame <- data.frame(Variable = rownames(summary(model42)$coef),
                           Coefficient = summary(model42)$coef[, 1],
                           SE = summary(model42)$coef[, 2],
                           modelName = "DG outgroup")[2,]
model52Frame <- data.frame(Variable = rownames(summary(model52)$coef),
                           Coefficient = summary(model52)$coef[, 1],
                           SE = summary(model52)$coef[, 2],
                           modelName = "Index")[2,]
model13Frame <- data.frame(Variable = "affected",
                           Coefficient = model13$coefficients[2],
                           SE = model13$rest.se[2],
                           modelName = "Prisoner's Dilemma ingroup")
model23Frame <- data.frame(Variable = "affected",
                           Coefficient = model23$coefficients[2],
                           SE = model23$rest.se[2],
                           modelName = "Dictator Game ingroup")
model33Frame <- data.frame(Variable = "affected",
                           Coefficient = model33$coefficients[2],
                           SE = model33$rest.se[2],
                           modelName = "Prisoner's Dilemma outgroup")
model43Frame <- data.frame(Variable = "affected",
                           Coefficient = model43$coefficients[2],
                           SE = model43$rest.se[2],
                           modelName = "Dictator Game outgroup")
model53Frame <- data.frame(Variable = "affected",
                           Coefficient = model53$coefficients[2],
                           SE = model53$rest.se[2],
                           modelName = "Index")
```

```{r Tweaking}

# So they wanted to bring all models done for
# the original data. And then arrange the order
# using factor. 

allModelFrame1 <- data.frame(rbind(model11Frame, model21Frame, model31Frame, model41Frame, model51Frame))
allModelFrame1$Variable <- c(1,2,3,4,5)
allModelFrame1$Variable <- factor(allModelFrame1$Variable, labels=c("Prisoner's Dilemma  Ingroup", "Dictator Game  Ingroup", "Prisoner's Dilemma  Outgroup", "Dictator Game  Outgroup", "Prosociality-  index"))
levels(allModelFrame1$Variable) <- gsub("  ", "\n", levels(allModelFrame1$Variable))
```

```{r Tweaking 2SLS}

# So now they want to combine all the models that have the spatial 
# component to them. I'm a little confused about what 2SL is, but
# the code is similar to before. 

allModelFrame2 <- data.frame(rbind(model12Frame, model22Frame, model32Frame, model42Frame, model52Frame))
allModelFrame2$Variable <- c(1,2,3,4,5)
allModelFrame2$Variable <- factor(allModelFrame2$Variable, labels=c("Prisoner's Dilemma  Ingroup", "Dictator Game  Ingroup", "Prisoner's Dilemma  Outgroup", "Dictator Game  Outgroup", "Prosociality-  index"))
levels(allModelFrame2$Variable) <- gsub("  ", "\n", levels(allModelFrame2$Variable))
```

```{r Tweaking SAM}

# Same as before but now for the instrument SAM. 
# I find this portion of the paper really confusing 
# to be honest, but again the code is understandable. 

allModelFrame3 <- data.frame(rbind(model13Frame, model23Frame, model33Frame, model43Frame, model53Frame))
allModelFrame3$Variable <- c(1,2,3,4,5)
allModelFrame3$Variable <- factor(allModelFrame3$Variable, labels=c("Prisoner's Dilemma  Ingroup", "Dictator Game  Ingroup", "Prisoner's Dilemma  Outgroup", "Dictator Game  Outgroup", "Prosociality-  index"))
levels(allModelFrame3$Variable) <- gsub("  ", "\n", levels(allModelFrame3$Variable))
```

```{r Final Tweaking}

# Okay great. They want to combine the three combinations together. 
# Also they're doing something weird to the data with rep? 

allModelFram <- rbind(allModelFrame1, allModelFrame2, allModelFrame3)
allModelFram$matrix_style <- rep(c("Instrument", "2SLS", "Instrument (SAM)"),each=5)
```

```{r CI}

# Calculating and setting their confidence intervals. 

interval1 <- -qnorm((1-0.90)/2)  # 90% multiplier
interval2 <- -qnorm((1-0.95)/2)  # 95% multiplier
```

```{r Dodge?}

# They set up their dodge position? I guess
# that helps with the graphing? 

pd = position_dodge(0.5)
```

```{r Graphing}

# Same graphing code as figure 5 but now obviously they are including 
# the additional instrumental variables. Code makes sense. Overall logic
# is harder for me, but I'm honing in on what I don't understand and will
# need help with later. 

figure6 <- ggplot(allModelFram, aes(shape=matrix_style)) + 
  geom_hline(yintercept = 0, colour = gray(1/2), lty = 2) + 
  geom_linerange(aes(x = Variable, ymin = Coefficient - SE*interval1,
                     ymax = Coefficient + SE*interval1),
                 lwd = 1, position = pd) + 
  geom_linerange(aes(x = Variable, ymin = Coefficient - SE*interval2,
                     ymax = Coefficient + SE*interval2),
                 lwd = 1/4, position = pd) + 
  geom_point(aes(x = Variable, y = Coefficient, shape = matrix_style),
             position = pd,fill = "WHITE", size = 3) + 
  coord_flip(ylim = c(-0.95,0.22)) + theme_bw() + 
  theme(legend.position="bottom") + 
  scale_shape_manual(values = c(23, 24, 25), name ="") +
  ylab("")  + xlab("") +     
  theme(text = element_text(size=18, family="Times"))
```

```{r Output}

# They want the output. 

figure6
```