---
title: "Table 1 Replication"
author: "Cian Stryker"
date: "2/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Table 1's time. Also my last
# bit of reproducible code. It starts
# the same way they all have so far. 

rm(list=ls())

# Only thing I don't know here
# is stargazer but I've wanted to 
# figure out how to use it for a 
# while so this is cool.

library(readstata13)
library(stargazer)
```

```{r Loading}

# Their loading data. 

data <- read.dta13("./kyrgyzstan.dta")
```


```{r My Loading}

# My loading code. 

load("~/Replication_Project/Data/kyrgyzstan.RData")
data <- table
```


```{r Cleaning}

# Same cleaning code that they've done
# for all figures. Its just as.integer commands
# and shifting the binary.

data$affected <- as.integer(data$affected)
data$affected <- data$affected - 1
data$pd_in <- as.integer(data$pd_in)
data$pd_out <- as.integer(data$pd_out)


# They wanted to rename a variable here. 

data$social_cap_retro <- data$leadership

# Subsetting time as per usual.

data_uzbek <- data[which(data$ethnicity=="Uzbek"),]

# And once more they wanted to scale everything. 
# Remind me to ask Alice to clarify what this does 
# in simple terms. I think I get it but I want to 
# make sure. 

data_uzbek$pd_in_scale <- scale(data_uzbek$pd_in)
data_uzbek$dg_in_scale <- scale(data_uzbek$dg_in)
data_uzbek$pd_out_scale <- scale(data_uzbek$pd_out)
data_uzbek$dg_out_scale <- scale(data_uzbek$dg_out)
data_uzbek$cooperation_index <- rowSums(cbind(data_uzbek$pd_in_scale, 
                                              data_uzbek$dg_in_scale, 
                                              data_uzbek$pd_out_scale, 
                                              data_uzbek$dg_out_scale), na.rm=T)/4
```


```{r Regressions}

# So many multivariate linear regressions. So this 
# is their table info which requires the prisoner dilemma, 
# dictator game, and cooperation index to be regressed by 
# a bushel of variables. Here is where I'd like to do some
# playing around when its my turn to make changes. 

model1 <- lm(pd_in_scale ~ affected + economy_index + state_index + social_cap_retro + access_index + aj_vote_share, data=data_uzbek)
model2 <- lm(dg_in_scale ~ affected + economy_index + state_index + social_cap_retro + access_index + aj_vote_share, data=data_uzbek)
model3 <- lm(pd_out_scale ~ affected + economy_index + state_index + social_cap_retro + access_index + aj_vote_share, data=data_uzbek)
model4 <- lm(dg_out_scale ~ affected + economy_index + state_index + social_cap_retro + access_index + aj_vote_share, data=data_uzbek)
model5 <- lm(cooperation_index ~ affected + economy_index + state_index + social_cap_retro + access_index + aj_vote_share, data=data_uzbek)
```

```{r Summaries}

# I actually don't know why they are
# running a summary on every model but
# I assume they need to in order to run
# the stargazer. 

summary(model1)
summary(model2)
summary(model3)
summary(model4)
summary(model5)
```

```{r Stargazer}

# Alright so this is werid. I know they are using stargazer 
# to make the really nice looking table in the paper. I don't know
# how this code works though. I can't seem to replicate it myself.
# This is something else I'll need Alice's help with. Or I just need 
# enough time to figure out how stargazer works. 

 stargazer(model1, model2, model3, model4, model5, 
          covariate.labels = c("Destruction", "Wealth index", "State capacity index", "Community policing index", "Accessibility index", "AJ %"),
          dep.var.labels = c("Cooperation in Prisoner's Dilemma", "Investment in Dictator Game", "Cooperation in Prisoner's Dilemma", "Investment in Dictator Game" , "Cooperation-Index"),
          star.char = c("*", "**", "***"),
          title = "Table 1: Effect of Destruction on Prosocial Behavior (controlling for confounders and mobilization)",
          star.cutoffs = c(0.05, 0.01, 0.001))
```